import { reaxel, createReaxable } from 'reaxes';

// War3 设置接口
export interface War3Settings {
  // 视频设置
  reswidth: number;
  resheight: number;
  colordepth: number;
  refreshrate: number;

  // 游戏模式
  reforged: number; // 0=经典版, 1=重制版

  // 图形设置
  maxfps: number;
  vsync: number;

  // 其他设置
  [key: string]: string | number;
}

// 相机设置
export interface CameraSettings {
  fov: number;
  angle: number;
  distance: number;
  enabled: boolean;
}

// War3设置管理
export const reaxel_War3Settings = reaxel(() => {
  const { store, setState } = createReaxable({
    settings: {} as War3Settings,
    cameraSettings: {
      fov: 70,
      angle: 0,
      distance: 1650,
      enabled: false
    } as CameraSettings,
    isLoading: false,
    lastModified: null as Date | null
  });

  // 读取War3Preferences.txt
  const loadSettings = async (war3Path: string): Promise<War3Settings> => {
    setState({ isLoading: true });

    try {
      const preferencesPath = `${war3Path}\\War3Preferences.txt`;
      const content = await window.electronAPI?.readFile(preferencesPath);

      if (!content) {
        throw new Error('War3Preferences.txt not found');
      }

      const settings = parsePreferencesFile(content);
      setState({
        settings,
        isLoading: false,
        lastModified: new Date()
      });

      return settings;
    } catch (error) {
      console.error('Failed to load War3 settings:', error);
      setState({ isLoading: false });
      throw error;
    }
  };

  // 解析配置文件
  const parsePreferencesFile = (content: string): War3Settings => {
    const settings: War3Settings = {
      reswidth: 1920,
      resheight: 1080,
      colordepth: 32,
      refreshrate: 60,
      reforged: 1,
      maxfps: 60,
      vsync: 0
    };

    const lines = content.split('\n');

    for (const line of lines) {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith('//')) {
        continue;
      }

      const equalIndex = trimmedLine.indexOf('=');
      if (equalIndex > 0) {
        const key = trimmedLine.substring(0, equalIndex).trim();
        const value = trimmedLine.substring(equalIndex + 1).trim();

        // 尝试转换为数字
        const numValue = parseFloat(value);
        if (!isNaN(numValue)) {
          settings[key] = numValue;
        } else {
          settings[key] = value;
        }
      }
    }

    return settings;
  };

  // 保存设置
  const saveSettings = async (war3Path: string, newSettings: Partial<War3Settings>): Promise<void> => {
    setState({ isLoading: true });

    try {
      const preferencesPath = `${war3Path}\\War3Preferences.txt`;

      // 合并设置
      const mergedSettings = { ...store.settings, ...newSettings };

      // 生成配置文件内容
      const content = generatePreferencesFile(mergedSettings);

      // 写入文件
      await window.electronAPI?.writeFile(preferencesPath, content);

      setState({
        settings: mergedSettings,
        isLoading: false,
        lastModified: new Date()
      });
    } catch (error) {
      console.error('Failed to save War3 settings:', error);
      setState({ isLoading: false });
      throw error;
    }
  };

  // 生成配置文件内容
  const generatePreferencesFile = (settings: War3Settings): string => {
    const lines = [
      '// Warcraft III Preferences',
      '// Generated by Quenching Mod Client',
      ''
    ];

    // 按类别组织设置
    const categories = {
      'Video Settings': ['reswidth', 'resheight', 'colordepth', 'refreshrate', 'maxfps', 'vsync'],
      'Game Mode': ['reforged'],
      'Other Settings': []
    };

    for (const [category, keys] of Object.entries(categories)) {
      lines.push(`// ${category}`);

      for (const key of keys) {
        if (key in settings) {
          lines.push(`${key}=${settings[key]}`);
        }
      }

      lines.push('');
    }

    // 添加其他未分类的设置
    const categorizedKeys = new Set(Object.values(categories).flat());
    for (const [key, value] of Object.entries(settings)) {
      if (!categorizedKeys.has(key)) {
        lines.push(`${key}=${value}`);
      }
    }

    return lines.join('\n');
  };

  // 切换HD/SD模式
  const toggleGameMode = async (war3Path: string, isReforged: boolean): Promise<void> => {
    await saveSettings(war3Path, { reforged: isReforged ? 1 : 0 });
  };

  // 设置分辨率
  const setResolution = async (war3Path: string, width: number, height: number): Promise<void> => {
    await saveSettings(war3Path, {
      reswidth: width,
      resheight: height
    });
  };

  // 相机设置管理
  const loadCameraSettings = async (war3Path: string): Promise<CameraSettings> => {
    try {
      const blizzardJPath = `${war3Path}\\Scripts\\blizzard.j`;
      const content = await window.electronAPI?.readFile(blizzardJPath);

      if (!content) {
        throw new Error('blizzard.j not found');
      }

      const cameraSettings = parseCameraSettings(content);
      setState({ cameraSettings });

      return cameraSettings;
    } catch (error) {
      console.error('Failed to load camera settings:', error);
      throw error;
    }
  };

  // 解析相机设置
  const parseCameraSettings = (content: string): CameraSettings => {
    const settings: CameraSettings = {
      fov: 70,
      angle: 0,
      distance: 1650,
      enabled: false
    };

    // 查找相机相关的设置
    const fovMatch = content.match(/SetCameraField\(CAMERA_FIELD_FIELD_OF_VIEW,\s*([0-9.]+)/);
    if (fovMatch) {
      settings.fov = parseFloat(fovMatch[1]);
      settings.enabled = true;
    }

    const angleMatch = content.match(/SetCameraField\(CAMERA_FIELD_ANGLE_OF_ATTACK,\s*([0-9.-]+)/);
    if (angleMatch) {
      settings.angle = parseFloat(angleMatch[1]);
    }

    const distanceMatch = content.match(/SetCameraField\(CAMERA_FIELD_TARGET_DISTANCE,\s*([0-9.]+)/);
    if (distanceMatch) {
      settings.distance = parseFloat(distanceMatch[1]);
    }

    return settings;
  };

  // 保存相机设置
  const saveCameraSettings = async (war3Path: string, newCameraSettings: Partial<CameraSettings>): Promise<void> => {
    try {
      const blizzardJPath = `${war3Path}\\Scripts\\blizzard.j`;
      const content = await window.electronAPI?.readFile(blizzardJPath);

      if (!content) {
        throw new Error('blizzard.j not found');
      }

      const mergedSettings = { ...store.cameraSettings, ...newCameraSettings };
      const modifiedContent = applyCameraSettings(content, mergedSettings);

      // 备份原文件
      const backupPath = `${blizzardJPath}.backup`;
      await window.electronAPI?.copyFile(blizzardJPath, backupPath);

      // 写入修改后的内容
      await window.electronAPI?.writeFile(blizzardJPath, modifiedContent);

      setState({ cameraSettings: mergedSettings });
    } catch (error) {
      console.error('Failed to save camera settings:', error);
      throw error;
    }
  };

  // 应用相机设置到blizzard.j
  const applyCameraSettings = (content: string, settings: CameraSettings): string => {
    let modifiedContent = content;

    if (settings.enabled) {
      // 查找并替换或添加相机设置
      const cameraInitFunction = 'function InitBlizzard takes nothing returns nothing';
      const functionIndex = modifiedContent.indexOf(cameraInitFunction);

      if (functionIndex !== -1) {
        const functionEnd = modifiedContent.indexOf('endfunction', functionIndex);

        if (functionEnd !== -1) {
          const beforeFunction = modifiedContent.substring(0, functionIndex);
          const afterFunction = modifiedContent.substring(functionEnd);

          const cameraCode = `
${cameraInitFunction}
    // Quenching Camera Settings
    call SetCameraField(CAMERA_FIELD_FIELD_OF_VIEW, ${settings.fov}, 0)
    call SetCameraField(CAMERA_FIELD_ANGLE_OF_ATTACK, ${settings.angle}, 0)
    call SetCameraField(CAMERA_FIELD_TARGET_DISTANCE, ${settings.distance}, 0)
`;

          modifiedContent = beforeFunction + cameraCode + afterFunction;
        }
      }
    } else {
      // 移除相机设置
      modifiedContent = modifiedContent.replace(
        /\/\/ Quenching Camera Settings[\s\S]*?(?=endfunction|$)/g,
        ''
      );
    }

    return modifiedContent;
  };

  // 重置相机设置
  const resetCameraSettings = async (war3Path: string): Promise<void> => {
    try {
      const blizzardJPath = `${war3Path}\\Scripts\\blizzard.j`;
      const backupPath = `${blizzardJPath}.backup`;

      const backupExists = await window.electronAPI?.pathExists(backupPath);
      if (backupExists) {
        await window.electronAPI?.copyFile(backupPath, blizzardJPath);
      }

      setState({
        cameraSettings: {
          fov: 70,
          angle: 0,
          distance: 1650,
          enabled: false
        }
      });
    } catch (error) {
      console.error('Failed to reset camera settings:', error);
      throw error;
    }
  };

  return {
    store,
    loadSettings,
    saveSettings,
    toggleGameMode,
    setResolution,
    loadCameraSettings,
    saveCameraSettings,
    resetCameraSettings
  };
});

// React Hook
export const useWar3Settings = () => {
  const settings = reaxel_War3Settings();
  return {
    settings: settings.store.settings,
    cameraSettings: settings.store.cameraSettings,
    isLoading: settings.store.isLoading,
    lastModified: settings.store.lastModified,
    loadSettings: settings.loadSettings,
    saveSettings: settings.saveSettings,
    toggleGameMode: settings.toggleGameMode,
    setResolution: settings.setResolution,
    loadCameraSettings: settings.loadCameraSettings,
    saveCameraSettings: settings.saveCameraSettings,
    resetCameraSettings: settings.resetCameraSettings
  };
};
